# This automation creates 3p packages and saves it to the Github Actions cache

name: Build 3p packages

on:
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:
    inputs:
      organization:
        description: 'The org/user of the repo'
        required: true
        type: string
        default: "o3de"
      repository:
        description: 'The repo to pull additional licenses'
        required: false
        type: string
        
run-name: Create package files

jobs: 
  Scan:
    name: Build packages
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    environment: ${{ github.ref_name }} # Check environment against branch
    
    permissions:
      contents: write
    
    steps:
      - name: Maximize Windows build space
        if: matrix.os == 'windows'
        run: |
          New-Item c:\packages -ItemType 'Directory' -Force
          New-Item -ItemType SymbolicLink -Name 3p-package-source\packages -Target c:\packages -Force
      
      - name: Maximize Linux build space
        if: matrix.os == 'ubuntu'
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'  
    
      - name: Checkout 3p scripts repo
        uses: actions/checkout@v3
        with:
          repository: o3de/3p-package-scripts
          ref: main
          fetch-depth: 0
          path: 3p-package-scripts
      
      - name: Checkout 3p packages repo
        uses: actions/checkout@v3
        with: 
          ref: main
          fetch-depth: 0
          path: 3p-package-source
          
      - name: Setup environment
        shell: bash
        run: |
          python3 -m pip install -r 3p-package-scripts/requirements.txt
          git config --global user.email "o3de@o3de.org"
          git config --global user.name "O3DF"   
          
      - name: Run build script
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            python3 3p-package-scripts/o3de_package_scripts/build_all_packages.py
            --server_urls https://canonical.o3de.org/
            --search_path 3p-package-source
            --output_folder 3p-package-source\packages\
          else
            python3 3p-package-scripts/o3de_package_scripts/build_all_packages.py
            --server_urls https://canonical.o3de.org/
            --search_path 3p-package-source
          fi
      
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-packages
          path: |
            3p-package-source/packages/*
