# This automation builds 3p packages based on a PR or manually run

name: Build 3P Packages PR

on:
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:
    inputs:
      build_path:
        description: 'The json file to build'
        type: choice
        options: 
        - "package_build_list_host_windows.json"
        - "package_build_list_host_linux.json"
        - "package_build_list_host_linux-aarch64.json"
        - "package_build_list_host_darwin.json"

  pull_request:
    paths:
      - 'package_build_list_host_*.json'

permissions:
  actions: 'write'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      command: ${{ steps.detect-platform.outputs.command }}
    
    steps:
    - name: Checkout 3P source repo
      uses: actions/checkout@v3

    - name: Detect platform and command from JSON changes
      id: detect-platform
      run: |
        CHANGED_FILES=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --name-only)
        if [ -z $CHANGED_FILES ]; then
          echo "No changes detected"
        fi
        for FILE in $CHANGED_FILES; do
          if [[ $FILE == package_build_list_host_* ]]; then
            PLATFORM=$(echo $FILE | sed -n 's/package_build_list_host_\(.*\).json/\1/p')
            case $PLATFORM in
              linux)
                OS_RUNNER="ubuntu-latest"
                ;;
              windows)
                OS_RUNNER="windows-latest"
                ;;
              darwin)
                OS_RUNNER="macos-latest"
                ;;
              *)
                OS_RUNNER="windows-latest" # default
                ;;
            esac
            COMMAND=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --no-ext-diff --unified=0 --exit-code -a --no-prefix | egrep "^\+" | grep Scripts | cut -d'"' -f4)
            echo "::set-output name=matrix::[\"$OS_RUNNER\"]"
            echo "::set-output name=command::$COMMAND"
            break
          fi
        done

  run-on-specific-os:
    needs: detect-changes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    steps:
      
    - name: Checkout 3P source repo
      uses: actions/checkout@v3

    - name: Run detected command
      run: |
        ${{ needs.detect-changes.outputs.command }}
          
      
